# Generated by Django 5.1.4 on 2025-01-29 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=50)),
                ('course_title', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('schedule_day', models.CharField(max_length=3)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.rooms')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.teachers')),
            ],
            options={
                'db_table': 'courses',
            },
        ),
    ]
