# Generated by Django 5.1.4 on 2025-02-21 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_students_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asynchs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asynchs', to='myapp.courses')),
            ],
            options={
                'db_table': 'asynchs',
            },
        ),
    ]
