# Generated by Django 5.1.4 on 2025-03-21 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_roomlogs_teacherattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_date', models.DateField()),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.courses')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.rooms')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.students')),
            ],
            options={
                'db_table': 'manual_attendance',
                'unique_together': {('day_date', 'student', 'course')},
            },
        ),
    ]
