# Generated by Django 5.1.4 on 2025-03-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_manualattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomlogs',
            name='is_synced',
            field=models.BooleanField(default=False),
        ),
    ]
