# Generated by Django 5.1.4 on 2025-03-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_roomlogs_is_synced'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='is_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='is_synced',
            field=models.BooleanField(default=False),
        ),
    ]
