# Generated by Django 5.1.4 on 2025-03-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_studentattendance_is_synced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualattendance',
            name='is_synced',
            field=models.BooleanField(default=False),
        ),
    ]
