# Generated by Django 5.1.4 on 2025-03-28 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_manualattendance_is_synced'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='au_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='students',
            name='au_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teachers',
            name='au_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
